language: go

go:
  - 1.7
  - tip

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install
  - ./getglide.sh

install:
  - glide install

script:
  - ./test.sh
  - gometalinter.v1 --vendor --deadline 5m --disable gotype --errors ./...
  - gometalinter.v1 --vendor --deadline 5m --disable gotype --disable gas --exclude "_test\.go" --exclude "not checked.+Close" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

