language: go

go:
  - 1.8

sudo: required

services:
  - docker

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - dep ensure

script:
  - ./scripts/test.sh
  - gometalinter --fast --vendor --deadline 5m --disable gotype --disable gas --exclude "\.pb.*\.go" --exclude "_strings\.go" --exclude "_test\.go" --exclude "not checked.+Close" ./...
  - scripts/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ]; then scripts/push.sh; fi

