// Code generated by "stringer -type=Store,Error -output=queue_strings.go"; DO NOT EDIT.

package q

import "fmt"

const _Store_name = "UnknownStoreMemory"

var _Store_index = [...]uint8{0, 12, 18}

func (i Store) String() string {
	if i < 0 || i >= Store(len(_Store_index)-1) {
		return fmt.Sprintf("Store(%d)", i)
	}
	return _Store_name[_Store_index[i]:_Store_index[i+1]]
}

const _Error_name = "UnknownErrorFullNotFound"

var _Error_index = [...]uint8{0, 12, 16, 24}

func (i Error) String() string {
	if i < 0 || i >= Error(len(_Error_index)-1) {
		return fmt.Sprintf("Error(%d)", i)
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
