---
kind: Service
apiVersion: v1
metadata:
  name: q
  labels:
    app: q
spec:
  selector:
    app: q
  ports:
  - name: grpc
    port: 10002
    targetPort: 10002
  - name: metrics
    port: 10003
    targetPort: 10003
  - name: rest
    port: 80
    targetPort: 80
  type: NodePort